# Generated by Django 4.0.3 on 2022-05-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_email_secret_user_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_method',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('github', 'Github')], default='email', max_length=20),
        ),
    ]
